export const ADD_TRANSACTION = "DELETE_TRANSACTION";
export const DELETE_TRANSACTION = "ADD_TRANSACTION";
export const GET_TRANSACTIONS_WITH_DATE = "GET_TRANSACTIONS_WITH_DATE";
export const DELETE_ALL_ELEMENTS = "DELETE_ALL_ELEMENTS";
